apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcabnettek-deployment
spec:
  selector:
    matchLabels:
      app: hcabnetteky-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: hcabnettek-devops-project
    spec:
      containers:
      - name: hcabnettek-devops-project
        image: yankils/simple-devops-image
        imagePullPolicy: Always
        ports:
        - containerPort: 8080